# Catppuccin Mocha colors for Tide.
# Palette source: https://github.com/catppuccin/palette

set -g tide_aws_color FAB387
set -g tide_bun_color F5E0DC
set -g tide_character_color A6E3A1
set -g tide_character_color_failure F38BA8
set -g tide_cmd_duration_color 7F849C
set -g tide_context_color_default FAB387
set -g tide_context_color_root F9E2AF
set -g tide_context_color_ssh FAB387
set -g tide_crystal_color CDD6F4
set -g tide_direnv_color F9E2AF
set -g tide_direnv_color_denied F38BA8
set -g tide_distrobox_color F5C2E7
set -g tide_docker_color 89B4FA
set -g tide_elixir_color CBA6F7
set -g tide_gcloud_color 89B4FA
set -g tide_git_color_branch A6E3A1
set -g tide_git_color_conflicted F38BA8
set -g tide_git_color_dirty F9E2AF
set -g tide_git_color_operation F38BA8
set -g tide_git_color_staged F9E2AF
set -g tide_git_color_stash A6E3A1
set -g tide_git_color_untracked 89DCEB
set -g tide_git_color_upstream A6E3A1
set -g tide_go_color 89DCEB
set -g tide_java_color FAB387
set -g tide_jobs_color A6E3A1
set -g tide_kubectl_color 89B4FA
set -g tide_nix_shell_color 74C7EC
set -g tide_node_color A6E3A1
set -g tide_os_color CDD6F4
set -g tide_php_color B4BEFE
set -g tide_private_mode_color CDD6F4
set -g tide_prompt_color_frame_and_connection 45475A
set -g tide_prompt_color_separator_same_color 9399B2
set -g tide_pulumi_color F9E2AF
set -g tide_pwd_color_anchors 89B4FA
set -g tide_pwd_color_dirs 74C7EC
set -g tide_pwd_color_truncated_dirs 7F849C
set -g tide_python_color 94E2D5
set -g tide_ruby_color F38BA8
set -g tide_rustc_color FAB387
set -g tide_shlvl_color FAB387
set -g tide_status_color A6E3A1
set -g tide_status_color_failure F38BA8
set -g tide_terraform_color CBA6F7
set -g tide_time_color 7F849C
set -g tide_toolbox_color CBA6F7
set -g tide_vi_mode_color_default 9399B2
set -g tide_vi_mode_color_insert 94E2D5
set -g tide_vi_mode_color_replace A6E3A1
set -g tide_vi_mode_color_visual FAB387
set -g tide_zig_color FAB387
